export const MATCH_REPOSITORY = 'MATCH_REPOSITORY';
export const CREATE_MATCH_USE_CASE = 'CREATE_MATCH_USE_CASE';
export const UPDATE_MATCH_USE_CASE = 'UPDATE_MATCH_USE_CASE';
export const DELETE_MATCH_USE_CASE = 'DELETE_MATCH_USE_CASE';
export const GET_MATCH_USE_CASE = 'GET_MATCH_USE_CASE';
export const GET_ALL_MATCHES_USE_CASE = 'GET_ALL_MATCHES_USE_CASE';
export const GENERATE_FIXTURE_USE_CASE = Symbol('GENERATE_FIXTURE_USE_CASE');
export const GENERATE_MATCHES_USE_CASE = Symbol('GENERATE_MATCHES_USE_CASE');
