export const PHASE_REPOSITORY = Symbol('PHASE_REPOSITORY');
export const CREATE_PHASE_USE_CASE = Symbol('CREATE_PHASE_USE_CASE');
export const GET_PHASE_BY_STATUS_USE_CASE = Symbol(
  'GET_PHASE_BY_STATUS_USE_CASE',
);
export const GET_PHASE_BY_TOURNAMENT_USE_CASE = Symbol(
  'GET_PHASE_BY_TOURNAMENT_USE_CASE',
);
export const GET_PHASE_BY_TYPE_USE_CASE = Symbol('GET_PHASE_BY_TYPE_USE_CASE');
export const HAS_ASSIGNED_FIXTURE_PHASE_USE_CASE = Symbol(
  'HAS_ASSIGNED_FIXTURE_PHASE_USE_CASE',
);
