export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const GET_TEAM_USE_CASE = 'GET_TEAM_USE_CASE';
export const GET_ALL_TEAMS_USE_CASE = 'GET_ALL_TEAMS_USE_CASE';
export const CREATE_TEAM_USE_CASE = 'CREATE_TEAM_USE_CASE';
export const UPDATE_TEAM_USE_CASE = 'UPDATE_TEAM_USE_CASE';
export const DELETE_TEAM_USE_CASE = 'DELETE_TEAM_USE_CASE';
export const TOURNAMENT_LOOKUP = 'TOURNAMENT_LOOKUP';
