export const GROUP_REPOSITORY = 'GROUP_REPOSITORY';
export const CREATE_GROUP_USE_CASE = 'CREATE_GROUP_USE_CASE';
export const UPDATE_GROUP_USE_CASE = 'UPDATE_GROUP_USE_CASE';
export const DELETE_GROUP_USE_CASE = 'DELETE_GROUP_USE_CASE';
export const GET_GROUP_USE_CASE = 'GET_GROUP_USE_CASE';
export const GET_ALL_GROUPS_USE_CASE = 'GET_ALL_GROUPS_USE_CASE';
export const GET_GROUPS_BY_PHASE_USE_CASE = 'GET_GROUPS_BY_PHASE_USE_CASE';
