export const PHASE_TYPE_REPOSITORY = Symbol('PHASE_TYPE_REPOSITORY');
export const CREATE_PHASE_TYPE_USE_CASE = Symbol('CREATE_PHASE_TYPE_USE_CASE');
export const DELETE_PHASE_TYPE_USE_CASE = Symbol('DELETE_PHASE_TYPE_USE_CASE');
export const GET_PHASE_TYPE_USE_CASE = Symbol('GET_PHASE_TYPE_USE_CASE');
export const GET_ALL_PHASE_TYPE_USE_CASE = Symbol(
  'GET_ALL_PHASE_TYPE_USE_CASE',
);
export const GET_PHASE_TYPE_BY_NAME_USE_CASE = Symbol(
  'GET_PHASE_TYPE_BY_NAME_USE_CASE',
);
