export const STANDING_REPOSITORY = Symbol('STANDING_REPOSITORY');
export const CREATE_STANDING_USE_CASE = Symbol('CREATE_STANDING_USE_CASE');
export const UPDATE_STANDING_USE_CASE = Symbol('UPDATE_STANDING_USE_CASE');
export const DELETE_STANDING_USE_CASE = Symbol('DELETE_STANDING_USE_CASE');
export const GET_STANDING_USE_CASE = Symbol('GET_STANDING_USE_CASE');
export const GET_ALL_STANDINGS_USE_CASE = Symbol('GET_ALL_STANDINGS_USE_CASE');
export const GET_STANDING_BY_TOURNAMENT_USE_CASE = Symbol('GET_STANDING_BY_TOURNAMENT_USE_CASE');
export const GET_STANDING_BY_TOURNAMENT_AND_TEAM_USE_CASE = Symbol('GET_STANDING_BY_TOURNAMENT_AND_TEAM_USE_CASE');
